### ISSUE TITLE
Farben der Logpunkte

### ISSUE THREAD

**Issue by aoacse** [h9h/soa-dashboard#137]
Hallo,

aktuell sind die Farben der Logpunkte Orange für SEP, Blau für ESB und ROT für Faults.

Die orangenen Logpunkte sind visuell schlecht von roten Logpunkten zu unterscheiden.

Vorschlag: 
SEP Logpunkte in Schwarz
ESB Logpunkte in Blau belassen
Faults in Rot belassen.

Was meinst du?

Danke und beste Grüße,
Carsten

**Comment by h9h** [comment]
Service-Consumer bzw. Provider Logpunkte sind schon schwarz. Ich suche eine andere Farbe für SEP aus.

**Comment by h9h** [comment]
Fix durch https://github.com/h9h/soa-dashboard/commit/63d38966ae5512e68444906eb79db6d0900fd6c9
