### ISSUE TITLE
[FEATURE] Antworzeit Warnung

### ISSUE THREAD

**Issue by noeliabelenrivero** [h9h/soa-dashboard#179]
**Is your feature request related to a problem? Please describe.**
Auf dem Dashboard ist es nicht möglich, auf einen Blick eine **Warnung** zu sehen, wenn die **Antwortzeit** zu hoch ist oder einen bestimmten Schwellenwert überschreitet.

**Describe the solution you'd like**
Eine Ampel auf dem **Antwortzeitdiagramm** könnte helfen, auf einen Blick zu erkennen, wenn die Werte höher als normal sind. Als Idee wird eine **gelbe Linie** vorgeschlagen, die anzeigt, wenn der erste Schwellenwert überschritten wird (z. B. über 100 ms), und eine **rote Linie**, die einen zweiten höheren Schwellenwert anzeigt (z. B. über 120 ms).

**Comment by h9h** [comment]
Habe mal zwei Linien implementiert, @noeliabelenrivero würde das passen?
Die zwei Zeiten sind in den Einstellungen konfigurierbar, Default 90/120 ms

**Comment by noeliabelenrivero** [comment]
Die Linien sehen gut aus und die Konfiguration funktioniert richtig. Vielen Dank @h9h!
