### ISSUE TITLE
[BUG] Reihenfolge der Logpunkte ändert sich in der Untertabelle

### ISSUE THREAD

**Issue by h9h** [h9h/soa-dashboard#22]
**Description**
Die Reihenfolge der Logpunkte ändert sich in der Untertabelle, wenn man darauf klickt, um die zugehörige Message anzuschauen.

**To Reproduce**
*  Klappe eine Message in der Dashboard-Ansicht auf
*  Klicke einen Logpunkt mit Message an
*  Zugleich mit dem Öffnen des modalen Fensters ändert sich die Reihenfolge der Logpunkte

**Expected behavior**
Keine Änderung der Reihenfolge der Logpunkte

**Desktop (please complete the following information):**
 - Browser Edge
 - Version 1.2.86

**Comment by h9h** [comment]
Bug wahrscheinlich mit Änderung der Default-Sortierreihenfolge eingeführt - damit hat nämlich die Untertabelle eine andere Sortierung als die Haupttabelle. Siehe https://github.com/h9h/soa-dashboard/commit/ca47d2d775913a0c676b85aa82cd66db3b7d6b52

**Comment by aoacse** [comment]
der Bug stört sehr, wenn man sich intensiv mit einem Funktionstest einer komplexen SOA Architektur beschäftigt. Siehst du eine Chance, den Bug zeitnah zu beheben?

**Comment by h9h** [comment]
Das ist tatsächlich nicht so ganz einfach, weil die Untertabelle in der Verwaltung der Tabelle (Fremdbibliothek) ist.

Als Workaround: Tatsächlich nutze ich diese Untertabelle überhaupt nicht (ich klappe den Servicecall nie auf). Ich schaue mir die Logpunkte und deren Messages immer in der Logpunkt Ansicht an, zu der man kommt indem man entweder auf die Spalte "Timing" in der entsprechenden Zeile des Servicecalls klickt (dann geht ein modales Fenster auf) oder auf die Spalte "Logpunkte" - dann geht der Servicecall in einem neuen Fenster auf.

In beiden Fällen erhält man dort die Message zum Logpunkt durch Anklicken des Logpunkts.

**Comment by h9h** [comment]
Obsolet, Untertabelle entfernt, da Funktionalität in den Spalten Timing bzw. Logpunkte vorhanden
