### ISSUE TITLE
Link zum original Nachrichtenaustausch von undelivered Messages Seite

### ISSUE THREAD

**Issue by aoacse** [h9h/soa-dashboard#281]
Hallo Michael,

es wäre für den Betriebssupport enorm hilfreich, wenn wir neben der üblichen Tabelle im SOA Dashboard im undelivered Bereich (Rejected, expird oder undelivered) auch den Link je Nachricht im Dashboard zum eigentlichen Nachrichtenaustausch hätten. So kann man effizienter nachvollziehen, was hier passiert ist.

Zusätzlich wäre es noch gut, sofern man referenceExpressions definiert hat, diese nach der Auswertung (also den Wert) sich vielleicht in der tabellarischen Übersicht im undelivered Bereich einblenden zu lassen.

Danke und beste Grüße,
Carsten

**Comment by h9h** [comment]
Hallo Carsten,

also sofern vorhanden aus der Message die Message-ID extrahieren und die Dashboard Ansicht für diese Message-ID aufrufen?
Kann ich probieren.

Liebe Grüße
Michael

**Comment by aoacse** [comment]
Ja genau, das wäre sehr hilfreich, wenn wir dann diese ID mit einem aufrufbaren Link zum konkreten Nachrichtenaustausch versehen könnten. Danke dir.

**Comment by h9h** [comment]
![Anmerkung 2022-07-19 110744](https://user-images.githubusercontent.com/5786906/179712800-b69a598f-8a2a-4a1c-aaa6-c53d618d05e7.png)
