### ISSUE TITLE
Anzeige der ProcessInstanceId

### ISSUE THREAD

**Issue by aoacse** [h9h/soa-dashboard#84]
1. Ich hätte gerne eine visuelle Darstellung der processInstanceID in der Tabelle der Hauptansicht.

2. Am Besten so, dass man danach die zugehörigen Service-Calls gruppieren kann.

Danke,
Carsten

**Comment by h9h** [comment]
processInstanceID wird jetzt angezeigt.
Über Klick auf den Titel der entsprechenden Spalte kann danach sortiert werden.

**Comment by aoacse** [comment]
Danke Michael, klappt!!
